(function () {
  "use strict";
  window.Game = window.Game || {};
  const G = window.Game;

  const ACHIEVEMENTS = [
    { id: "erster_verkauf", name: "First Sale", desc: "Sell a resource for the first time.", rewardMoney: 50, rewardXp: 10, check: (s) => (s.stats && s.stats.soldOnce) === true },
    { id: "erster_kauf", name: "First Purchase", desc: "Buy a resource for the first time.", rewardMoney: 25, rewardXp: 5, check: (s) => (s.stats && s.stats.boughtOnce) === true },
    { id: "kleinvieh", name: "Small Change", desc: "Own 500 $.", rewardMoney: 30, rewardXp: 8, check: (s) => s.money >= 500 },
    { id: "sparer", name: "Saver", desc: "Own 2,000 $.", rewardMoney: 80, rewardXp: 20, check: (s) => s.money >= 2000 },
    { id: "fuenftausend", name: "5,000 $", desc: "Own 5,000 $.", rewardMoney: 120, rewardXp: 30, check: (s) => s.money >= 5000 },
    { id: "wohlhabend", name: "Well-off", desc: "Own 10,000 $.", rewardMoney: 250, rewardXp: 60, check: (s) => s.money >= 10000 },
    { id: "reich", name: "25,000 $", desc: "Own 25,000 $.", rewardMoney: 350, rewardXp: 80, check: (s) => s.money >= 25000 },
    { id: "reicher_mann", name: "Rich", desc: "Own 50,000 $.", rewardMoney: 500, rewardXp: 120, check: (s) => s.money >= 50000 },
    { id: "hunderttausend", name: "100,000 $", desc: "Own 100,000 $.", rewardMoney: 800, rewardXp: 180, check: (s) => s.money >= 100000 },
    { id: "fuenfhunderttausend", name: "500,000 $", desc: "Own 500,000 $.", rewardMoney: 1200, rewardXp: 250, check: (s) => s.money >= 500000 },
    { id: "millionaer", name: "Millionaire", desc: "Own 1,000,000 $.", rewardMoney: 2000, rewardXp: 300, check: (s) => s.money >= 1000000 },
    { id: "zwei_millionen", name: "2 Million $", desc: "Own 2,000,000 $.", rewardMoney: 2500, rewardXp: 350, check: (s) => s.money >= 2000000 },
    { id: "fuenf_millionen", name: "5 Million $", desc: "Own 5,000,000 $.", rewardMoney: 3500, rewardXp: 450, check: (s) => s.money >= 5000000 },
    { id: "zehn_millionen", name: "10 Million $", desc: "Own 10,000,000 $.", rewardMoney: 5000, rewardXp: 600, check: (s) => s.money >= 10000000 },
    { id: "erstes_gebaeude", name: "First Building", desc: "Buy your first building.", rewardMoney: 100, rewardXp: 25, check: (s) => G.getTotalBuildingCount(s) >= 1 },
    { id: "baumeister", name: "Builder", desc: "Own 5 buildings (total).", rewardMoney: 150, rewardXp: 35, check: (s) => G.getTotalBuildingCount(s) >= 5 },
    { id: "zehn_gebaeude", name: "10 Buildings", desc: "Own 10 buildings.", rewardMoney: 250, rewardXp: 55, check: (s) => G.getTotalBuildingCount(s) >= 10 },
    { id: "tycoon", name: "Tycoon", desc: "Own 20 buildings.", rewardMoney: 500, rewardXp: 100, check: (s) => G.getTotalBuildingCount(s) >= 20 },
    { id: "imperium", name: "Empire", desc: "Own 35 buildings.", rewardMoney: 750, rewardXp: 150, check: (s) => G.getTotalBuildingCount(s) >= 35 },
    { id: "magnat", name: "Magnate", desc: "Own 50 buildings.", rewardMoney: 1000, rewardXp: 200, check: (s) => G.getTotalBuildingCount(s) >= 50 },
    { id: "gebaeude_75", name: "75 Buildings", desc: "Own 75 buildings.", rewardMoney: 1500, rewardXp: 280, check: (s) => G.getTotalBuildingCount(s) >= 75 },
    { id: "gebaeude_100", name: "100 Buildings", desc: "Own 100 buildings.", rewardMoney: 2500, rewardXp: 400, check: (s) => G.getTotalBuildingCount(s) >= 100 },
    { id: "vielfalt_3", name: "Variety", desc: "Own 3 different building types.", rewardMoney: 80, rewardXp: 25, check: (s) => G.getBuildingTypeCount(s) >= 3 },
    { id: "vielfalt_10", name: "Mixed Portfolio", desc: "Own 10 different building types.", rewardMoney: 200, rewardXp: 60, check: (s) => G.getBuildingTypeCount(s) >= 10 },
    { id: "vielfalt_20", name: "All-rounder", desc: "Own 20 different building types.", rewardMoney: 400, rewardXp: 120, check: (s) => G.getBuildingTypeCount(s) >= 20 },
    { id: "vielfalt_30", name: "30 Building Types", desc: "Own 30 different building types.", rewardMoney: 600, rewardXp: 180, check: (s) => G.getBuildingTypeCount(s) >= 30 },
    { id: "vielfalt_40", name: "Full Range", desc: "Own 40 different building types.", rewardMoney: 900, rewardXp: 250, check: (s) => G.getBuildingTypeCount(s) >= 40 },
    { id: "erstes_upgrade", name: "First Upgrade", desc: "Upgrade a building for the first time.", rewardMoney: 75, rewardXp: 20, check: (s) => (s.stats && s.stats.upgrades >= 1) === true },
    { id: "upgrade_5", name: "5 Upgrades", desc: "Perform 5 building upgrades.", rewardMoney: 100, rewardXp: 40, check: (s) => (s.stats && s.stats.upgrades >= 5) === true },
    { id: "upgrade_10", name: "10 Upgrades", desc: "Perform 10 building upgrades.", rewardMoney: 180, rewardXp: 70, check: (s) => (s.stats && s.stats.upgrades >= 10) === true },
    { id: "upgrade_25", name: "25 Upgrades", desc: "Perform 25 building upgrades.", rewardMoney: 350, rewardXp: 130, check: (s) => (s.stats && s.stats.upgrades >= 25) === true },
    { id: "upgrade_50", name: "50 Upgrades", desc: "Perform 50 building upgrades.", rewardMoney: 600, rewardXp: 200, check: (s) => (s.stats && s.stats.upgrades >= 50) === true },
    { id: "upgrade_100", name: "100 Upgrades", desc: "Perform 100 building upgrades.", rewardMoney: 1000, rewardXp: 350, check: (s) => (s.stats && s.stats.upgrades >= 100) === true },
    { id: "level_5", name: "Level 5", desc: "Reach player level 5.", rewardMoney: 100, rewardXp: 50, check: (s) => s.playerLevel >= 5 },
    { id: "level_10", name: "Level 10", desc: "Reach player level 10.", rewardMoney: 300, rewardXp: 100, check: (s) => s.playerLevel >= 10 },
    { id: "level_15", name: "Level 15", desc: "Reach player level 15.", rewardMoney: 500, rewardXp: 150, check: (s) => s.playerLevel >= 15 },
    { id: "level_20", name: "Level 20", desc: "Reach player level 20.", rewardMoney: 800, rewardXp: 200, check: (s) => s.playerLevel >= 20 },
    { id: "level_25", name: "Level 25", desc: "Reach player level 25.", rewardMoney: 1200, rewardXp: 280, check: (s) => s.playerLevel >= 25 },
    { id: "level_30", name: "Level 30", desc: "Reach player level 30.", rewardMoney: 1600, rewardXp: 350, check: (s) => s.playerLevel >= 30 },
    { id: "level_35", name: "Level 35", desc: "Reach player level 35.", rewardMoney: 2000, rewardXp: 420, check: (s) => s.playerLevel >= 35 },
    { id: "level_40", name: "Level 40", desc: "Reach player level 40.", rewardMoney: 2500, rewardXp: 500, check: (s) => s.playerLevel >= 40 },
    { id: "woche", name: "First Week", desc: "Play until day 7.", rewardMoney: 70, rewardXp: 35, check: (s) => s.day >= 7 },
    { id: "monat", name: "One Month", desc: "Play until day 30.", rewardMoney: 150, rewardXp: 75, check: (s) => s.day >= 30 },
    { id: "hundert_tage", name: "100 Days", desc: "Play until day 100.", rewardMoney: 300, rewardXp: 150, check: (s) => s.day >= 100 },
    { id: "volles_jahr", name: "Full Year", desc: "Play until day 365.", rewardMoney: 500, rewardXp: 250, check: (s) => s.day >= 365 },
    { id: "tag_200", name: "200 Days", desc: "Play until day 200.", rewardMoney: 400, rewardXp: 200, check: (s) => s.day >= 200 },
    { id: "tag_500", name: "500 Days", desc: "Play until day 500.", rewardMoney: 700, rewardXp: 320, check: (s) => s.day >= 500 },
    { id: "tag_1000", name: "1000 Days", desc: "Play until day 1000.", rewardMoney: 1200, rewardXp: 500, check: (s) => s.day >= 1000 },
    { id: "ein_jahr", name: "Year 2", desc: "Reach year 2.", rewardMoney: 500, rewardXp: 150, check: (s) => s.year >= 2 },
    { id: "jahr_3", name: "Year 3", desc: "Reach year 3.", rewardMoney: 700, rewardXp: 200, check: (s) => s.year >= 3 },
    { id: "jahr_5", name: "Year 5", desc: "Reach year 5.", rewardMoney: 1000, rewardXp: 300, check: (s) => s.year >= 5 },
    { id: "jahr_7", name: "Year 7", desc: "Reach year 7.", rewardMoney: 1300, rewardXp: 380, check: (s) => s.year >= 7 },
    { id: "jahr_10", name: "Year 10", desc: "Reach year 10.", rewardMoney: 1800, rewardXp: 500, check: (s) => s.year >= 10 },
    { id: "lagerwert_1000", name: "Stocked", desc: "Own resources worth 1,000 $.", rewardMoney: 100, rewardXp: 30, check: (s) => G.getTotalResourceValue(s) >= 1000 },
    { id: "lagerwert_10000", name: "Large Warehouse", desc: "Own resources worth 10,000 $.", rewardMoney: 250, rewardXp: 80, check: (s) => G.getTotalResourceValue(s) >= 10000 },
    { id: "lagerwert_50000", name: "Resource Mogul", desc: "Own resources worth 50,000 $.", rewardMoney: 500, rewardXp: 150, check: (s) => G.getTotalResourceValue(s) >= 50000 },
    { id: "lagerwert_100000", name: "Warehouse Millionaire", desc: "Own resources worth 100,000 $.", rewardMoney: 800, rewardXp: 220, check: (s) => G.getTotalResourceValue(s) >= 100000 },
    { id: "lagerwert_250000", name: "Resource Baron", desc: "Own resources worth 250,000 $.", rewardMoney: 1200, rewardXp: 300, check: (s) => G.getTotalResourceValue(s) >= 250000 },
    { id: "lagerwert_500000", name: "Resource King", desc: "Own resources worth 500,000 $.", rewardMoney: 1800, rewardXp: 400, check: (s) => G.getTotalResourceValue(s) >= 500000 },
    { id: "lagerwert_million", name: "Resource Empire", desc: "Own resources worth 1,000,000 $.", rewardMoney: 2500, rewardXp: 550, check: (s) => G.getTotalResourceValue(s) >= 1000000 },
  ];

  Object.assign(window.Game, { ACHIEVEMENTS });
})();
