(function () {
  "use strict";
  window.Game = window.Game || {};
  const G = window.Game;

  const ACHIEVEMENTS = [
    { id: "erster_verkauf", name: "Erstes Geschäft", desc: "Verkaufe zum ersten Mal eine Ressource.", rewardMoney: 50, rewardXp: 10, check: (s) => (s.stats && s.stats.soldOnce) === true },
    { id: "erster_kauf", name: "Erster Einkauf", desc: "Kaufe zum ersten Mal eine Ressource.", rewardMoney: 25, rewardXp: 5, check: (s) => (s.stats && s.stats.boughtOnce) === true },
    { id: "kleinvieh", name: "Kleinvieh", desc: "Besitze 500 $.", rewardMoney: 30, rewardXp: 8, check: (s) => s.money >= 500 },
    { id: "sparer", name: "Sparer", desc: "Besitze 2.000 $.", rewardMoney: 80, rewardXp: 20, check: (s) => s.money >= 2000 },
    { id: "fuenftausend", name: "5.000 $", desc: "Besitze 5.000 $.", rewardMoney: 120, rewardXp: 30, check: (s) => s.money >= 5000 },
    { id: "wohlhabend", name: "Wohlhabend", desc: "Besitze 10.000 $.", rewardMoney: 250, rewardXp: 60, check: (s) => s.money >= 10000 },
    { id: "reich", name: "25.000 $", desc: "Besitze 25.000 $.", rewardMoney: 350, rewardXp: 80, check: (s) => s.money >= 25000 },
    { id: "reicher_mann", name: "Reicher Mann", desc: "Besitze 50.000 $.", rewardMoney: 500, rewardXp: 120, check: (s) => s.money >= 50000 },
    { id: "hunderttausend", name: "100.000 $", desc: "Besitze 100.000 $.", rewardMoney: 800, rewardXp: 180, check: (s) => s.money >= 100000 },
    { id: "fuenfhunderttausend", name: "500.000 $", desc: "Besitze 500.000 $.", rewardMoney: 1200, rewardXp: 250, check: (s) => s.money >= 500000 },
    { id: "millionaer", name: "Millionär", desc: "Besitze 1.000.000 $.", rewardMoney: 2000, rewardXp: 300, check: (s) => s.money >= 1000000 },
    { id: "zwei_millionen", name: "2 Millionen $", desc: "Besitze 2.000.000 $.", rewardMoney: 2500, rewardXp: 350, check: (s) => s.money >= 2000000 },
    { id: "fuenf_millionen", name: "5 Millionen $", desc: "Besitze 5.000.000 $.", rewardMoney: 3500, rewardXp: 450, check: (s) => s.money >= 5000000 },
    { id: "zehn_millionen", name: "10 Millionen $", desc: "Besitze 10.000.000 $.", rewardMoney: 5000, rewardXp: 600, check: (s) => s.money >= 10000000 },
    { id: "erstes_gebaeude", name: "Erstes Gebäude", desc: "Kaufe dein erstes Gebäude.", rewardMoney: 100, rewardXp: 25, check: (s) => G.getTotalBuildingCount(s) >= 1 },
    { id: "baumeister", name: "Baumeister", desc: "Besitze 5 Gebäude (gesamt).", rewardMoney: 150, rewardXp: 35, check: (s) => G.getTotalBuildingCount(s) >= 5 },
    { id: "zehn_gebaeude", name: "10 Gebäude", desc: "Besitze 10 Gebäude.", rewardMoney: 250, rewardXp: 55, check: (s) => G.getTotalBuildingCount(s) >= 10 },
    { id: "tycoon", name: "Tycoon", desc: "Besitze 20 Gebäude.", rewardMoney: 500, rewardXp: 100, check: (s) => G.getTotalBuildingCount(s) >= 20 },
    { id: "imperium", name: "Imperium", desc: "Besitze 35 Gebäude.", rewardMoney: 750, rewardXp: 150, check: (s) => G.getTotalBuildingCount(s) >= 35 },
    { id: "magnat", name: "Magnat", desc: "Besitze 50 Gebäude.", rewardMoney: 1000, rewardXp: 200, check: (s) => G.getTotalBuildingCount(s) >= 50 },
    { id: "gebaeude_75", name: "75 Gebäude", desc: "Besitze 75 Gebäude.", rewardMoney: 1500, rewardXp: 280, check: (s) => G.getTotalBuildingCount(s) >= 75 },
    { id: "gebaeude_100", name: "100 Gebäude", desc: "Besitze 100 Gebäude.", rewardMoney: 2500, rewardXp: 400, check: (s) => G.getTotalBuildingCount(s) >= 100 },
    { id: "vielfalt_3", name: "Vielfalt", desc: "Besitze 3 verschiedene Gebäudetypen.", rewardMoney: 80, rewardXp: 25, check: (s) => G.getBuildingTypeCount(s) >= 3 },
    { id: "vielfalt_10", name: "Bunter Mix", desc: "Besitze 10 verschiedene Gebäudetypen.", rewardMoney: 200, rewardXp: 60, check: (s) => G.getBuildingTypeCount(s) >= 10 },
    { id: "vielfalt_20", name: "Allrounder", desc: "Besitze 20 verschiedene Gebäudetypen.", rewardMoney: 400, rewardXp: 120, check: (s) => G.getBuildingTypeCount(s) >= 20 },
    { id: "vielfalt_30", name: "30 Gebäudetypen", desc: "Besitze 30 verschiedene Gebäudetypen.", rewardMoney: 600, rewardXp: 180, check: (s) => G.getBuildingTypeCount(s) >= 30 },
    { id: "vielfalt_40", name: "Volles Sortiment", desc: "Besitze 40 verschiedene Gebäudetypen.", rewardMoney: 900, rewardXp: 250, check: (s) => G.getBuildingTypeCount(s) >= 40 },
    { id: "erstes_upgrade", name: "Erstes Upgrade", desc: "Verbessere ein Gebäude zum ersten Mal.", rewardMoney: 75, rewardXp: 20, check: (s) => (s.stats && s.stats.upgrades >= 1) === true },
    { id: "upgrade_5", name: "5 Upgrades", desc: "Führe 5 Gebäude-Upgrades durch.", rewardMoney: 100, rewardXp: 40, check: (s) => (s.stats && s.stats.upgrades >= 5) === true },
    { id: "upgrade_10", name: "10 Upgrades", desc: "Führe 10 Gebäude-Upgrades durch.", rewardMoney: 180, rewardXp: 70, check: (s) => (s.stats && s.stats.upgrades >= 10) === true },
    { id: "upgrade_25", name: "25 Upgrades", desc: "Führe 25 Gebäude-Upgrades durch.", rewardMoney: 350, rewardXp: 130, check: (s) => (s.stats && s.stats.upgrades >= 25) === true },
    { id: "upgrade_50", name: "50 Upgrades", desc: "Führe 50 Gebäude-Upgrades durch.", rewardMoney: 600, rewardXp: 200, check: (s) => (s.stats && s.stats.upgrades >= 50) === true },
    { id: "upgrade_100", name: "100 Upgrades", desc: "Führe 100 Gebäude-Upgrades durch.", rewardMoney: 1000, rewardXp: 350, check: (s) => (s.stats && s.stats.upgrades >= 100) === true },
    { id: "level_5", name: "Level 5", desc: "Erreiche Spieler-Level 5.", rewardMoney: 100, rewardXp: 50, check: (s) => s.playerLevel >= 5 },
    { id: "level_10", name: "Level 10", desc: "Erreiche Spieler-Level 10.", rewardMoney: 300, rewardXp: 100, check: (s) => s.playerLevel >= 10 },
    { id: "level_15", name: "Level 15", desc: "Erreiche Spieler-Level 15.", rewardMoney: 500, rewardXp: 150, check: (s) => s.playerLevel >= 15 },
    { id: "level_20", name: "Level 20", desc: "Erreiche Spieler-Level 20.", rewardMoney: 800, rewardXp: 200, check: (s) => s.playerLevel >= 20 },
    { id: "level_25", name: "Level 25", desc: "Erreiche Spieler-Level 25.", rewardMoney: 1200, rewardXp: 280, check: (s) => s.playerLevel >= 25 },
    { id: "level_30", name: "Level 30", desc: "Erreiche Spieler-Level 30.", rewardMoney: 1600, rewardXp: 350, check: (s) => s.playerLevel >= 30 },
    { id: "level_35", name: "Level 35", desc: "Erreiche Spieler-Level 35.", rewardMoney: 2000, rewardXp: 420, check: (s) => s.playerLevel >= 35 },
    { id: "level_40", name: "Level 40", desc: "Erreiche Spieler-Level 40.", rewardMoney: 2500, rewardXp: 500, check: (s) => s.playerLevel >= 40 },
    { id: "woche", name: "Erste Woche", desc: "Spiele bis Tag 7.", rewardMoney: 70, rewardXp: 35, check: (s) => s.day >= 7 },
    { id: "monat", name: "Ein Monat", desc: "Spiele bis Tag 30.", rewardMoney: 150, rewardXp: 75, check: (s) => s.day >= 30 },
    { id: "hundert_tage", name: "100 Tage", desc: "Spiele bis Tag 100.", rewardMoney: 300, rewardXp: 150, check: (s) => s.day >= 100 },
    { id: "volles_jahr", name: "Volles Jahr", desc: "Spiele bis Tag 365.", rewardMoney: 500, rewardXp: 250, check: (s) => s.day >= 365 },
    { id: "tag_200", name: "200 Tage", desc: "Spiele bis Tag 200.", rewardMoney: 400, rewardXp: 200, check: (s) => s.day >= 200 },
    { id: "tag_500", name: "500 Tage", desc: "Spiele bis Tag 500.", rewardMoney: 700, rewardXp: 320, check: (s) => s.day >= 500 },
    { id: "tag_1000", name: "1000 Tage", desc: "Spiele bis Tag 1000.", rewardMoney: 1200, rewardXp: 500, check: (s) => s.day >= 1000 },
    { id: "ein_jahr", name: "Jahr 2", desc: "Erreiche Jahr 2.", rewardMoney: 500, rewardXp: 150, check: (s) => s.year >= 2 },
    { id: "jahr_3", name: "Jahr 3", desc: "Erreiche Jahr 3.", rewardMoney: 700, rewardXp: 200, check: (s) => s.year >= 3 },
    { id: "jahr_5", name: "Jahr 5", desc: "Erreiche Jahr 5.", rewardMoney: 1000, rewardXp: 300, check: (s) => s.year >= 5 },
    { id: "jahr_7", name: "Jahr 7", desc: "Erreiche Jahr 7.", rewardMoney: 1300, rewardXp: 380, check: (s) => s.year >= 7 },
    { id: "jahr_10", name: "Jahr 10", desc: "Erreiche Jahr 10.", rewardMoney: 1800, rewardXp: 500, check: (s) => s.year >= 10 },
    { id: "lagerwert_1000", name: "Lager voll", desc: "Ressourcen im Wert von 1.000 $ besitzen.", rewardMoney: 100, rewardXp: 30, check: (s) => G.getTotalResourceValue(s) >= 1000 },
    { id: "lagerwert_10000", name: "Großes Lager", desc: "Ressourcen im Wert von 10.000 $ besitzen.", rewardMoney: 250, rewardXp: 80, check: (s) => G.getTotalResourceValue(s) >= 10000 },
    { id: "lagerwert_50000", name: "Ressourcen-Mogul", desc: "Ressourcen im Wert von 50.000 $ besitzen.", rewardMoney: 500, rewardXp: 150, check: (s) => G.getTotalResourceValue(s) >= 50000 },
    { id: "lagerwert_100000", name: "Lager-Millionär", desc: "Ressourcen im Wert von 100.000 $ besitzen.", rewardMoney: 800, rewardXp: 220, check: (s) => G.getTotalResourceValue(s) >= 100000 },
    { id: "lagerwert_250000", name: "Ressourcen-Baron", desc: "Ressourcen im Wert von 250.000 $ besitzen.", rewardMoney: 1200, rewardXp: 300, check: (s) => G.getTotalResourceValue(s) >= 250000 },
    { id: "lagerwert_500000", name: "Ressourcen-König", desc: "Ressourcen im Wert von 500.000 $ besitzen.", rewardMoney: 1800, rewardXp: 400, check: (s) => G.getTotalResourceValue(s) >= 500000 },
    { id: "lagerwert_million", name: "Ressourcen-Imperium", desc: "Ressourcen im Wert von 1.000.000 $ besitzen.", rewardMoney: 2500, rewardXp: 550, check: (s) => G.getTotalResourceValue(s) >= 1000000 },
  ];

  Object.assign(window.Game, { ACHIEVEMENTS });
})();
