(function () {
  "use strict";
  window.Game = window.Game || {};

  const GOODS = [
    { id: "weizen", name: "Getreide", basePrice: 10, category: "Nahrung" },
    { id: "fisch", name: "Fisch", basePrice: 22, category: "Nahrung" },
    { id: "honig", name: "Honig", basePrice: 38, category: "Nahrung" },
    { id: "wein", name: "Wein", basePrice: 75, category: "Nahrung" },
    { id: "tabak", name: "Tabak", basePrice: 55, category: "Nahrung" },
    { id: "kaffee", name: "Kaffee", basePrice: 62, category: "Nahrung" },
    { id: "zucker", name: "Zucker", basePrice: 20, category: "Nahrung" },
    { id: "milch", name: "Milch", basePrice: 12, category: "Nahrung" },
    { id: "fleisch", name: "Fleisch", basePrice: 48, category: "Nahrung" },
    { id: "tee", name: "Tee", basePrice: 44, category: "Nahrung" },
    { id: "reis", name: "Reis", basePrice: 16, category: "Nahrung" },
    { id: "mais", name: "Mais", basePrice: 11, category: "Nahrung" },
    { id: "eier", name: "Eier", basePrice: 14, category: "Nahrung" },
    { id: "obst", name: "Obst", basePrice: 28, category: "Nahrung" },
    { id: "kakao", name: "Kakao", basePrice: 72, category: "Nahrung" },
    { id: "kartoffeln", name: "Kartoffeln", basePrice: 12, category: "Nahrung" },
    { id: "gerste", name: "Gerste", basePrice: 9, category: "Nahrung" },
    { id: "gemuese", name: "Gemüse", basePrice: 18, category: "Nahrung" },
    { id: "nuesse", name: "Nüsse", basePrice: 35, category: "Nahrung" },
    { id: "erz", name: "Erz", basePrice: 50, category: "Metalle & Erze" },
    { id: "gold", name: "Gold", basePrice: 120, category: "Metalle & Erze" },
    { id: "kupfer", name: "Kupfer", basePrice: 45, category: "Metalle & Erze" },
    { id: "silber", name: "Silber", basePrice: 95, category: "Metalle & Erze" },
    { id: "eisen", name: "Eisen", basePrice: 58, category: "Metalle & Erze" },
    { id: "zinn", name: "Zinn", basePrice: 52, category: "Metalle & Erze" },
    { id: "blei", name: "Blei", basePrice: 40, category: "Metalle & Erze" },
    { id: "nickel", name: "Nickel", basePrice: 68, category: "Metalle & Erze" },
    { id: "aluminium", name: "Aluminium", basePrice: 78, category: "Metalle & Erze" },
    { id: "zink", name: "Zink", basePrice: 48, category: "Metalle & Erze" },
    { id: "titan", name: "Titan", basePrice: 135, category: "Metalle & Erze" },
    { id: "platin", name: "Platin", basePrice: 200, category: "Metalle & Erze" },
    { id: "chrom", name: "Chrom", basePrice: 72, category: "Metalle & Erze" },
    { id: "holz", name: "Holz", basePrice: 25, category: "Baumaterial" },
    { id: "stein", name: "Stein", basePrice: 35, category: "Baumaterial" },
    { id: "lehm", name: "Lehm", basePrice: 12, category: "Baumaterial" },
    { id: "sand", name: "Sand", basePrice: 8, category: "Baumaterial" },
    { id: "kies", name: "Kies", basePrice: 10, category: "Baumaterial" },
    { id: "zement", name: "Zement", basePrice: 42, category: "Baumaterial" },
    { id: "marmor", name: "Marmor", basePrice: 88, category: "Baumaterial" },
    { id: "kohle", name: "Kohle", basePrice: 28, category: "Energie" },
    { id: "oel", name: "Öl", basePrice: 80, category: "Energie" },
    { id: "gas", name: "Gas", basePrice: 65, category: "Energie" },
    { id: "uran", name: "Uran", basePrice: 150, category: "Energie" },
    { id: "baumwolle", name: "Baumwolle", basePrice: 18, category: "Textilien" },
    { id: "wolle", name: "Wolle", basePrice: 42, category: "Textilien" },
    { id: "leder", name: "Leder", basePrice: 65, category: "Textilien" },
    { id: "seide", name: "Seide", basePrice: 140, category: "Textilien" },
    { id: "hanf", name: "Hanf", basePrice: 30, category: "Textilien" },
    { id: "jute", name: "Jute", basePrice: 24, category: "Textilien" },
    { id: "flachs", name: "Flachs", basePrice: 36, category: "Textilien" },
    { id: "kaschmir", name: "Kaschmir", basePrice: 185, category: "Textilien" },
    { id: "synthetik", name: "Synthetikfaser", basePrice: 35, category: "Textilien" },
    { id: "gewuerze", name: "Gewürze", basePrice: 110, category: "Gewürze & Luxus" },
    { id: "salz", name: "Salz", basePrice: 15, category: "Gewürze & Luxus" },
    { id: "edelsteine", name: "Edelsteine", basePrice: 250, category: "Gewürze & Luxus" },
    { id: "perlen", name: "Perlen", basePrice: 180, category: "Gewürze & Luxus" },
    { id: "bernstein", name: "Bernstein", basePrice: 165, category: "Gewürze & Luxus" },
    { id: "safran", name: "Safran", basePrice: 320, category: "Gewürze & Luxus" },
    { id: "truffel", name: "Trüffel", basePrice: 280, category: "Gewürze & Luxus" },
    { id: "muscheln", name: "Muscheln", basePrice: 45, category: "Gewürze & Luxus" },
    { id: "bitcoin", name: "Bitcoin", basePrice: 25000, category: "Währungen" },
  ];

  const GOODS_CATEGORY_ORDER = ["Nahrung", "Metalle & Erze", "Baumaterial", "Energie", "Textilien", "Gewürze & Luxus", "Währungen"];

  const BUILDING_TYPES = {
    farm: { name: "Farm", baseCost: 15000, produces: "weizen", baseOutput: 3, upgradeCostBase: 6000, upgradeOutputBonus: 2, category: "Landwirtschaft" },
    plantage: { name: "Plantage", baseCost: 18000, produces: "baumwolle", baseOutput: 3, upgradeCostBase: 7500, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    schafzucht: { name: "Schafzucht", baseCost: 21000, produces: "wolle", baseOutput: 2, upgradeCostBase: 9000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    weinberg: { name: "Weinberg", baseCost: 40000, produces: "wein", baseOutput: 1, upgradeCostBase: 16000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    imkerei: { name: "Imkerei", baseCost: 14500, produces: "honig", baseOutput: 2, upgradeCostBase: 5800, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    gewuerzplantage: { name: "Gewürzplantage", baseCost: 48000, produces: "gewuerze", baseOutput: 1, upgradeCostBase: 19500, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    rinderzucht: { name: "Rinderzucht", baseCost: 28000, produces: "leder", baseOutput: 1, upgradeCostBase: 11500, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    sawmill: { name: "Sägewerk", baseCost: 24000, produces: "holz", baseOutput: 2, upgradeCostBase: 10500, upgradeOutputBonus: 1, category: "Forst & Fischerei" },
    fischerei: { name: "Fischerei", baseCost: 16500, produces: "fisch", baseOutput: 3, upgradeCostBase: 6600, upgradeOutputBonus: 1, category: "Forst & Fischerei" },
    mine: { name: "Mine", baseCost: 36000, produces: "erz", baseOutput: 1, upgradeCostBase: 15000, upgradeOutputBonus: 1, category: "Bergbau" },
    steinbruch: { name: "Steinbruch", baseCost: 29000, produces: "stein", baseOutput: 2, upgradeCostBase: 11500, upgradeOutputBonus: 1, category: "Bergbau" },
    goldmine: { name: "Goldmine", baseCost: 75000, produces: "gold", baseOutput: 1, upgradeCostBase: 27000, upgradeOutputBonus: 1, category: "Bergbau" },
    kohlestollen: { name: "Kohlestollen", baseCost: 33000, produces: "kohle", baseOutput: 2, upgradeCostBase: 12000, upgradeOutputBonus: 1, category: "Bergbau" },
    silbermine: { name: "Silbermine", baseCost: 66000, produces: "silber", baseOutput: 1, upgradeCostBase: 25500, upgradeOutputBonus: 1, category: "Bergbau" },
    kupfermine: { name: "Kupfermine", baseCost: 42000, produces: "kupfer", baseOutput: 2, upgradeCostBase: 14500, upgradeOutputBonus: 1, category: "Bergbau" },
    eisenhuette: { name: "Eisenhütte", baseCost: 50000, produces: "eisen", baseOutput: 1, upgradeCostBase: 16500, upgradeOutputBonus: 1, category: "Bergbau" },
    oelfeld: { name: "Ölfeld", baseCost: 55000, produces: "oel", baseOutput: 1, upgradeCostBase: 18000, upgradeOutputBonus: 1, category: "Industrie" },
    saline: { name: "Saline", baseCost: 12500, produces: "salz", baseOutput: 4, upgradeCostBase: 4800, upgradeOutputBonus: 1, category: "Industrie" },
    tabakplantage: { name: "Tabakplantage", baseCost: 33000, produces: "tabak", baseOutput: 2, upgradeCostBase: 12600, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    kaffeeplantage: { name: "Kaffeeplantage", baseCost: 42000, produces: "kaffee", baseOutput: 1, upgradeCostBase: 15000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    zuckerplantage: { name: "Zuckerplantage", baseCost: 22500, produces: "zucker", baseOutput: 3, upgradeCostBase: 8400, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    molkerei: { name: "Molkerei", baseCost: 17500, produces: "milch", baseOutput: 4, upgradeCostBase: 6000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    schlachthof: { name: "Schlachthof", baseCost: 29000, produces: "fleisch", baseOutput: 2, upgradeCostBase: 10800, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    zinnmine: { name: "Zinnmine", baseCost: 40500, produces: "zinn", baseOutput: 2, upgradeCostBase: 14500, upgradeOutputBonus: 1, category: "Bergbau" },
    bleimine: { name: "Bleimine", baseCost: 34500, produces: "blei", baseOutput: 2, upgradeCostBase: 12000, upgradeOutputBonus: 1, category: "Bergbau" },
    ziegelei: { name: "Ziegelei", baseCost: 15500, produces: "lehm", baseOutput: 4, upgradeCostBase: 5400, upgradeOutputBonus: 1, category: "Bergbau" },
    sandgrube: { name: "Sandgrube", baseCost: 11500, produces: "sand", baseOutput: 5, upgradeCostBase: 4200, upgradeOutputBonus: 1, category: "Bergbau" },
    edelsteinmine: { name: "Edelsteinmine", baseCost: 95000, produces: "edelsteine", baseOutput: 1, upgradeCostBase: 36000, upgradeOutputBonus: 1, category: "Bergbau" },
    gaswerk: { name: "Gaswerk", baseCost: 63000, produces: "gas", baseOutput: 1, upgradeCostBase: 21000, upgradeOutputBonus: 1, category: "Industrie" },
    seidenfarm: { name: "Seidenfarm", baseCost: 56000, produces: "seide", baseOutput: 1, upgradeCostBase: 20500, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    hanffeld: { name: "Hanffeld", baseCost: 19200, produces: "hanf", baseOutput: 3, upgradeCostBase: 7200, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    perlenzucht: { name: "Perlenzucht", baseCost: 85000, produces: "perlen", baseOutput: 1, upgradeCostBase: 28500, upgradeOutputBonus: 1, category: "Forst & Fischerei" },
    teeplantage: { name: "Teeplantage", baseCost: 37500, produces: "tee", baseOutput: 2, upgradeCostBase: 13800, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    reisfeld: { name: "Reisfeld", baseCost: 18500, produces: "reis", baseOutput: 4, upgradeCostBase: 6600, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    maisfeld: { name: "Maisfeld", baseCost: 14000, produces: "mais", baseOutput: 4, upgradeCostBase: 5100, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    gefluegelhof: { name: "Geflügelhof", baseCost: 21500, produces: "eier", baseOutput: 3, upgradeCostBase: 7800, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    obstanlage: { name: "Obstanlage", baseCost: 26500, produces: "obst", baseOutput: 2, upgradeCostBase: 9600, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    kakaoplantage: { name: "Kakaoplantage", baseCost: 46500, produces: "kakao", baseOutput: 1, upgradeCostBase: 17400, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    nickelmine: { name: "Nickelmine", baseCost: 51500, produces: "nickel", baseOutput: 1, upgradeCostBase: 18600, upgradeOutputBonus: 1, category: "Bergbau" },
    aluminiumhuette: { name: "Aluminiumhütte", baseCost: 59500, produces: "aluminium", baseOutput: 1, upgradeCostBase: 21600, upgradeOutputBonus: 1, category: "Bergbau" },
    kiesgrube: { name: "Kiesgrube", baseCost: 13200, produces: "kies", baseOutput: 5, upgradeCostBase: 4950, upgradeOutputBonus: 1, category: "Bergbau" },
    juteanbau: { name: "Juteanbau", baseCost: 16800, produces: "jute", baseOutput: 3, upgradeCostBase: 6300, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    flachsfeld: { name: "Flachsfeld", baseCost: 20500, produces: "flachs", baseOutput: 2, upgradeCostBase: 8100, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    bernsteinsammler: { name: "Bernstein-Sammler", baseCost: 72000, produces: "bernstein", baseOutput: 1, upgradeCostBase: 26500, upgradeOutputBonus: 1, category: "Forst & Fischerei" },
    kartoffelacker: { name: "Kartoffelacker", baseCost: 14000, produces: "kartoffeln", baseOutput: 4, upgradeCostBase: 5200, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    gerstenfeld: { name: "Gerstenfeld", baseCost: 12000, produces: "gerste", baseOutput: 4, upgradeCostBase: 4500, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    gemueseanbau: { name: "Gemüseanbau", baseCost: 16000, produces: "gemuese", baseOutput: 3, upgradeCostBase: 6000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    nussgarten: { name: "Nussgarten", baseCost: 32000, produces: "nuesse", baseOutput: 2, upgradeCostBase: 12000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    zinkmine: { name: "Zinkmine", baseCost: 38000, produces: "zink", baseOutput: 2, upgradeCostBase: 14000, upgradeOutputBonus: 1, category: "Bergbau" },
    titanhuette: { name: "Titanhütte", baseCost: 68000, produces: "titan", baseOutput: 1, upgradeCostBase: 25000, upgradeOutputBonus: 1, category: "Bergbau" },
    platinmine: { name: "Platinmine", baseCost: 88000, produces: "platin", baseOutput: 1, upgradeCostBase: 32000, upgradeOutputBonus: 1, category: "Bergbau" },
    chrommine: { name: "Chrommine", baseCost: 45000, produces: "chrom", baseOutput: 1, upgradeCostBase: 17000, upgradeOutputBonus: 1, category: "Bergbau" },
    zementwerk: { name: "Zementwerk", baseCost: 35000, produces: "zement", baseOutput: 2, upgradeCostBase: 13000, upgradeOutputBonus: 1, category: "Industrie" },
    marmorsteinbruch: { name: "Marmorsteinbruch", baseCost: 52000, produces: "marmor", baseOutput: 1, upgradeCostBase: 19000, upgradeOutputBonus: 1, category: "Bergbau" },
    uranmine: { name: "Uranmine", baseCost: 78000, produces: "uran", baseOutput: 1, upgradeCostBase: 29000, upgradeOutputBonus: 1, category: "Bergbau" },
    kaschmirzucht: { name: "Kaschmirzucht", baseCost: 58000, produces: "kaschmir", baseOutput: 1, upgradeCostBase: 22000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    chemiefaserwerk: { name: "Chemiefaserwerk", baseCost: 38000, produces: "synthetik", baseOutput: 2, upgradeCostBase: 14000, upgradeOutputBonus: 1, category: "Industrie" },
    safrananbau: { name: "Safrananbau", baseCost: 92000, produces: "safran", baseOutput: 1, upgradeCostBase: 35000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    truffelsuche: { name: "Trüffelsuche", baseCost: 82000, produces: "truffel", baseOutput: 1, upgradeCostBase: 31000, upgradeOutputBonus: 1, category: "Landwirtschaft" },
    muschelfarm: { name: "Muschelfarm", baseCost: 24000, produces: "muscheln", baseOutput: 2, upgradeCostBase: 9000, upgradeOutputBonus: 1, category: "Forst & Fischerei" },
    miningfarm: { name: "Miningfarm", baseCost: 1285000, produces: "bitcoin", baseOutput: 1, upgradeCostBase: 100000, upgradeOutputBonus: 1, category: "Industrie", minLevel: 10 },
  };

  const BUILDING_CATEGORY_ORDER = ["Landwirtschaft", "Forst & Fischerei", "Bergbau", "Industrie"];

  Object.assign(window.Game, {
    GOODS,
    GOODS_CATEGORY_ORDER,
    BUILDING_TYPES,
    BUILDING_CATEGORY_ORDER,
    INCOME_INTERVAL_SEC: 24,
    XP_PER_DAY: 5,
    STORAGE_KEY: "wirtschaftssim_save",
    UI_STORAGE_KEY: "wirtschaftssim_ui",
    PRICE_HISTORY_DAYS: 90,
  });
})();
