(function () {
  "use strict";
  window.Game = window.Game || {};

  const GOODS = [
    { id: "weizen", name: "Grain", basePrice: 10, category: "Renewable & Organic" },
    { id: "fisch", name: "Fish", basePrice: 22, category: "Food" },
    { id: "honig", name: "Honey", basePrice: 38, category: "Food" },
    { id: "wein", name: "Wine", basePrice: 75, category: "Food" },
    { id: "tabak", name: "Tobacco", basePrice: 55, category: "Food" },
    { id: "kaffee", name: "Coffee", basePrice: 62, category: "Food" },
    { id: "zucker", name: "Sugar", basePrice: 20, category: "Renewable & Organic" },
    { id: "milch", name: "Milk", basePrice: 12, category: "Food" },
    { id: "fleisch", name: "Meat", basePrice: 48, category: "Food" },
    { id: "tee", name: "Tea", basePrice: 44, category: "Food" },
    { id: "reis", name: "Rice", basePrice: 16, category: "Food" },
    { id: "mais", name: "Corn", basePrice: 11, category: "Renewable & Organic" },
    { id: "eier", name: "Eggs", basePrice: 14, category: "Food" },
    { id: "obst", name: "Fruit", basePrice: 28, category: "Food" },
    { id: "kakao", name: "Cocoa", basePrice: 72, category: "Food" },
    { id: "kartoffeln", name: "Potatoes", basePrice: 12, category: "Food" },
    { id: "gerste", name: "Barley", basePrice: 9, category: "Food" },
    { id: "gemuese", name: "Vegetables", basePrice: 18, category: "Food" },
    { id: "nuesse", name: "Nuts", basePrice: 35, category: "Food" },
    { id: "erz", name: "Cobalt", basePrice: 52, category: "Metals & Ores" },
    { id: "gold", name: "Gold", basePrice: 120, category: "Metals & Ores" },
    { id: "kupfer", name: "Copper", basePrice: 45, category: "Metals & Ores" },
    { id: "silber", name: "Silver", basePrice: 95, category: "Metals & Ores" },
    { id: "eisen", name: "Iron", basePrice: 58, category: "Metals & Ores" },
    { id: "zinn", name: "Tin", basePrice: 52, category: "Metals & Ores" },
    { id: "blei", name: "Lead", basePrice: 40, category: "Metals & Ores" },
    { id: "nickel", name: "Nickel", basePrice: 68, category: "Metals & Ores" },
    { id: "aluminium", name: "Aluminium", basePrice: 78, category: "Metals & Ores" },
    { id: "zink", name: "Zinc", basePrice: 48, category: "Metals & Ores" },
    { id: "titan", name: "Titanium", basePrice: 135, category: "Metals & Ores" },
    { id: "platin", name: "Platinum", basePrice: 200, category: "Metals & Ores" },
    { id: "lithium", name: "Lithium", basePrice: 85, category: "Metals & Ores" },
    { id: "chrom", name: "Chromium", basePrice: 72, category: "Metals & Ores" },
    { id: "lanthan", name: "Lanthanum", basePrice: 95, category: "Rare Earths" },
    { id: "cer", name: "Cerium", basePrice: 88, category: "Rare Earths" },
    { id: "praseodym", name: "Praseodymium", basePrice: 125, category: "Rare Earths" },
    { id: "neodym", name: "Neodymium", basePrice: 140, category: "Rare Earths" },
    { id: "promethium", name: "Promethium", basePrice: 180, category: "Rare Earths" },
    { id: "samarium", name: "Samarium", basePrice: 110, category: "Rare Earths" },
    { id: "europium", name: "Europium", basePrice: 165, category: "Rare Earths" },
    { id: "gadolinium", name: "Gadolinium", basePrice: 118, category: "Rare Earths" },
    { id: "terbium", name: "Terbium", basePrice: 195, category: "Rare Earths" },
    { id: "dysprosium", name: "Dysprosium", basePrice: 155, category: "Rare Earths" },
    { id: "holmium", name: "Holmium", basePrice: 132, category: "Rare Earths" },
    { id: "erbium", name: "Erbium", basePrice: 122, category: "Rare Earths" },
    { id: "thulium", name: "Thulium", basePrice: 210, category: "Rare Earths" },
    { id: "ytterbium", name: "Ytterbium", basePrice: 98, category: "Rare Earths" },
    { id: "lutetium", name: "Lutetium", basePrice: 225, category: "Rare Earths" },
    { id: "holz", name: "Wood", basePrice: 25, category: "Renewable & Organic" },
    { id: "stein", name: "Stone", basePrice: 35, category: "Building & Industrial" },
    { id: "lehm", name: "Clay", basePrice: 12, category: "Building & Industrial" },
    { id: "sand", name: "Sand", basePrice: 8, category: "Building & Industrial" },
    { id: "kies", name: "Gravel", basePrice: 10, category: "Building & Industrial" },
    { id: "zement", name: "Cement", basePrice: 42, category: "Building & Industrial" },
    { id: "marmor", name: "Marble", basePrice: 88, category: "Building & Industrial" },
    { id: "kalk", name: "Lime", basePrice: 22, category: "Building & Industrial" },
    { id: "graphit", name: "Graphite", basePrice: 55, category: "Building & Industrial" },
    { id: "phosphat", name: "Phosphate", basePrice: 38, category: "Building & Industrial" },
    { id: "kohle", name: "Coal", basePrice: 28, category: "Fossil Energy" },
    { id: "oel", name: "Oil", basePrice: 80, category: "Fossil Energy" },
    { id: "gas", name: "Gas", basePrice: 65, category: "Fossil Energy" },
    { id: "uran", name: "Uranium", basePrice: 150, category: "Fossil Energy" },
    { id: "baumwolle", name: "Cotton", basePrice: 18, category: "Renewable & Organic" },
    { id: "wolle", name: "Wool", basePrice: 42, category: "Renewable & Organic" },
    { id: "leder", name: "Leather", basePrice: 65, category: "Renewable & Organic" },
    { id: "kautschuk", name: "Rubber", basePrice: 48, category: "Renewable & Organic" },
    { id: "raps", name: "Rapeseed", basePrice: 24, category: "Renewable & Organic" },
    { id: "seide", name: "Silk", basePrice: 140, category: "Textiles" },
    { id: "hanf", name: "Hemp", basePrice: 30, category: "Textiles" },
    { id: "jute", name: "Jute", basePrice: 24, category: "Textiles" },
    { id: "flachs", name: "Flax", basePrice: 36, category: "Textiles" },
    { id: "kaschmir", name: "Cashmere", basePrice: 185, category: "Textiles" },
    { id: "synthetik", name: "Synthetic Fibre", basePrice: 35, category: "Textiles" },
    { id: "gewuerze", name: "Spices", basePrice: 110, category: "Spices & Luxury" },
    { id: "salz", name: "Salt", basePrice: 15, category: "Building & Industrial" },
    { id: "edelsteine", name: "Gems", basePrice: 250, category: "Spices & Luxury" },
    { id: "perlen", name: "Pearls", basePrice: 180, category: "Spices & Luxury" },
    { id: "bernstein", name: "Amber", basePrice: 165, category: "Spices & Luxury" },
    { id: "safran", name: "Saffron", basePrice: 320, category: "Spices & Luxury" },
    { id: "truffel", name: "Truffles", basePrice: 280, category: "Spices & Luxury" },
    { id: "muscheln", name: "Shellfish", basePrice: 45, category: "Spices & Luxury" },
    { id: "bitcoin", name: "Bitcoin", basePrice: 25000, category: "Currencies" },
    { id: "ethereum", name: "Ethereum", basePrice: 2500, category: "Currencies" },
    { id: "litecoin", name: "Litecoin", basePrice: 95, category: "Currencies" },
    { id: "ripple", name: "Ripple (XRP)", basePrice: 1, category: "Currencies" },
    { id: "cardano", name: "Cardano", basePrice: 45, category: "Currencies" },
    { id: "solana", name: "Solana", basePrice: 180, category: "Currencies" },
    { id: "dogecoin", name: "Dogecoin", basePrice: 1, category: "Currencies" },
    { id: "polkadot", name: "Polkadot", basePrice: 75, category: "Currencies" },
    { id: "avalanche", name: "Avalanche", basePrice: 35, category: "Currencies" },
    { id: "chainlink", name: "Chainlink", basePrice: 18, category: "Currencies" },
  ];

  const GOODS_CATEGORY_ORDER = ["Building & Industrial", "Metals & Ores", "Fossil Energy", "Renewable & Organic", "Food", "Rare Earths", "Textiles", "Spices & Luxury", "Currencies"];

  const BUILDING_TYPES = {
    farm: { name: "Farm", baseCost: 15000, produces: "weizen", baseOutput: 3, upgradeCostBase: 6000, upgradeOutputBonus: 2, category: "Agriculture" },
    plantage: { name: "Plantation", baseCost: 18000, produces: "baumwolle", baseOutput: 3, upgradeCostBase: 7500, upgradeOutputBonus: 1, category: "Agriculture" },
    schafzucht: { name: "Sheep Farm", baseCost: 21000, produces: "wolle", baseOutput: 2, upgradeCostBase: 9000, upgradeOutputBonus: 1, category: "Agriculture" },
    weinberg: { name: "Vineyard", baseCost: 40000, produces: "wein", baseOutput: 1, upgradeCostBase: 16000, upgradeOutputBonus: 1, category: "Agriculture" },
    imkerei: { name: "Apiary", baseCost: 14500, produces: "honig", baseOutput: 2, upgradeCostBase: 5800, upgradeOutputBonus: 1, category: "Agriculture" },
    gewuerzplantage: { name: "Spice Plantation", baseCost: 48000, produces: "gewuerze", baseOutput: 1, upgradeCostBase: 19500, upgradeOutputBonus: 1, category: "Agriculture" },
    rinderzucht: { name: "Cattle Ranch", baseCost: 28000, produces: "leder", baseOutput: 1, upgradeCostBase: 11500, upgradeOutputBonus: 1, category: "Agriculture" },
    sawmill: { name: "Sawmill", baseCost: 24000, produces: "holz", baseOutput: 2, upgradeCostBase: 10500, upgradeOutputBonus: 1, category: "Forestry & Fishing" },
    fischerei: { name: "Fishery", baseCost: 16500, produces: "fisch", baseOutput: 3, upgradeCostBase: 6600, upgradeOutputBonus: 1, category: "Forestry & Fishing" },
    mine: { name: "Cobalt Mine", baseCost: 36000, produces: "erz", baseOutput: 1, upgradeCostBase: 15000, upgradeOutputBonus: 1, category: "Mining" },
    steinbruch: { name: "Quarry", baseCost: 29000, produces: "stein", baseOutput: 2, upgradeCostBase: 11500, upgradeOutputBonus: 1, category: "Mining" },
    goldmine: { name: "Gold Mine", baseCost: 75000, produces: "gold", baseOutput: 1, upgradeCostBase: 27000, upgradeOutputBonus: 1, category: "Mining" },
    kohlestollen: { name: "Coal Mine", baseCost: 33000, produces: "kohle", baseOutput: 2, upgradeCostBase: 12000, upgradeOutputBonus: 1, category: "Mining" },
    silbermine: { name: "Silver Mine", baseCost: 66000, produces: "silber", baseOutput: 1, upgradeCostBase: 25500, upgradeOutputBonus: 1, category: "Mining" },
    kupfermine: { name: "Copper Mine", baseCost: 42000, produces: "kupfer", baseOutput: 2, upgradeCostBase: 14500, upgradeOutputBonus: 1, category: "Mining" },
    eisenhuette: { name: "Ironworks", baseCost: 50000, produces: "eisen", baseOutput: 1, upgradeCostBase: 16500, upgradeOutputBonus: 1, category: "Mining" },
    oelfeld: { name: "Oil Field", baseCost: 55000, produces: "oel", baseOutput: 1, upgradeCostBase: 18000, upgradeOutputBonus: 1, category: "Industry" },
    saline: { name: "Salt Works", baseCost: 12500, produces: "salz", baseOutput: 4, upgradeCostBase: 4800, upgradeOutputBonus: 1, category: "Industry" },
    tabakplantage: { name: "Tobacco Plantation", baseCost: 33000, produces: "tabak", baseOutput: 2, upgradeCostBase: 12600, upgradeOutputBonus: 1, category: "Agriculture" },
    kaffeeplantage: { name: "Coffee Plantation", baseCost: 42000, produces: "kaffee", baseOutput: 1, upgradeCostBase: 15000, upgradeOutputBonus: 1, category: "Agriculture" },
    zuckerplantage: { name: "Sugar Plantation", baseCost: 22500, produces: "zucker", baseOutput: 3, upgradeCostBase: 8400, upgradeOutputBonus: 1, category: "Agriculture" },
    kautschukplantage: { name: "Rubber Plantation", baseCost: 35500, produces: "kautschuk", baseOutput: 2, upgradeCostBase: 13200, upgradeOutputBonus: 1, category: "Agriculture" },
    rapsfeld: { name: "Rapeseed Field", baseCost: 19800, produces: "raps", baseOutput: 3, upgradeCostBase: 7200, upgradeOutputBonus: 1, category: "Agriculture" },
    molkerei: { name: "Dairy", baseCost: 17500, produces: "milch", baseOutput: 4, upgradeCostBase: 6000, upgradeOutputBonus: 1, category: "Agriculture" },
    schlachthof: { name: "Slaughterhouse", baseCost: 29000, produces: "fleisch", baseOutput: 2, upgradeCostBase: 10800, upgradeOutputBonus: 1, category: "Agriculture" },
    zinnmine: { name: "Tin Mine", baseCost: 40500, produces: "zinn", baseOutput: 2, upgradeCostBase: 14500, upgradeOutputBonus: 1, category: "Mining" },
    bleimine: { name: "Lead Mine", baseCost: 34500, produces: "blei", baseOutput: 2, upgradeCostBase: 12000, upgradeOutputBonus: 1, category: "Mining" },
    ziegelei: { name: "Brickworks", baseCost: 15500, produces: "lehm", baseOutput: 4, upgradeCostBase: 5400, upgradeOutputBonus: 1, category: "Mining" },
    sandgrube: { name: "Sand Pit", baseCost: 11500, produces: "sand", baseOutput: 5, upgradeCostBase: 4200, upgradeOutputBonus: 1, category: "Mining" },
    edelsteinmine: { name: "Gem Mine", baseCost: 95000, produces: "edelsteine", baseOutput: 1, upgradeCostBase: 36000, upgradeOutputBonus: 1, category: "Mining" },
    gaswerk: { name: "Gas Works", baseCost: 63000, produces: "gas", baseOutput: 1, upgradeCostBase: 21000, upgradeOutputBonus: 1, category: "Industry" },
    seidenfarm: { name: "Silk Farm", baseCost: 56000, produces: "seide", baseOutput: 1, upgradeCostBase: 20500, upgradeOutputBonus: 1, category: "Agriculture" },
    hanffeld: { name: "Hemp Field", baseCost: 19200, produces: "hanf", baseOutput: 3, upgradeCostBase: 7200, upgradeOutputBonus: 1, category: "Agriculture" },
    perlenzucht: { name: "Pearl Farm", baseCost: 85000, produces: "perlen", baseOutput: 1, upgradeCostBase: 28500, upgradeOutputBonus: 1, category: "Forestry & Fishing" },
    teeplantage: { name: "Tea Plantation", baseCost: 37500, produces: "tee", baseOutput: 2, upgradeCostBase: 13800, upgradeOutputBonus: 1, category: "Agriculture" },
    reisfeld: { name: "Rice Paddy", baseCost: 18500, produces: "reis", baseOutput: 4, upgradeCostBase: 6600, upgradeOutputBonus: 1, category: "Agriculture" },
    maisfeld: { name: "Corn Field", baseCost: 14000, produces: "mais", baseOutput: 4, upgradeCostBase: 5100, upgradeOutputBonus: 1, category: "Agriculture" },
    gefluegelhof: { name: "Poultry Farm", baseCost: 21500, produces: "eier", baseOutput: 3, upgradeCostBase: 7800, upgradeOutputBonus: 1, category: "Agriculture" },
    obstanlage: { name: "Orchard", baseCost: 26500, produces: "obst", baseOutput: 2, upgradeCostBase: 9600, upgradeOutputBonus: 1, category: "Agriculture" },
    kakaoplantage: { name: "Cocoa Plantation", baseCost: 46500, produces: "kakao", baseOutput: 1, upgradeCostBase: 17400, upgradeOutputBonus: 1, category: "Agriculture" },
    nickelmine: { name: "Nickel Mine", baseCost: 51500, produces: "nickel", baseOutput: 1, upgradeCostBase: 18600, upgradeOutputBonus: 1, category: "Mining" },
    aluminiumhuette: { name: "Aluminium Smelter", baseCost: 59500, produces: "aluminium", baseOutput: 1, upgradeCostBase: 21600, upgradeOutputBonus: 1, category: "Mining" },
    kiesgrube: { name: "Gravel Pit", baseCost: 13200, produces: "kies", baseOutput: 5, upgradeCostBase: 4950, upgradeOutputBonus: 1, category: "Mining" },
    juteanbau: { name: "Jute Farm", baseCost: 16800, produces: "jute", baseOutput: 3, upgradeCostBase: 6300, upgradeOutputBonus: 1, category: "Agriculture" },
    flachsfeld: { name: "Flax Field", baseCost: 20500, produces: "flachs", baseOutput: 2, upgradeCostBase: 8100, upgradeOutputBonus: 1, category: "Agriculture" },
    bernsteinsammler: { name: "Amber Collector", baseCost: 72000, produces: "bernstein", baseOutput: 1, upgradeCostBase: 26500, upgradeOutputBonus: 1, category: "Forestry & Fishing" },
    kartoffelacker: { name: "Potato Field", baseCost: 14000, produces: "kartoffeln", baseOutput: 4, upgradeCostBase: 5200, upgradeOutputBonus: 1, category: "Agriculture" },
    gerstenfeld: { name: "Barley Field", baseCost: 12000, produces: "gerste", baseOutput: 4, upgradeCostBase: 4500, upgradeOutputBonus: 1, category: "Agriculture" },
    gemueseanbau: { name: "Vegetable Farm", baseCost: 16000, produces: "gemuese", baseOutput: 3, upgradeCostBase: 6000, upgradeOutputBonus: 1, category: "Agriculture" },
    nussgarten: { name: "Nut Grove", baseCost: 32000, produces: "nuesse", baseOutput: 2, upgradeCostBase: 12000, upgradeOutputBonus: 1, category: "Agriculture" },
    zinkmine: { name: "Zinc Mine", baseCost: 38000, produces: "zink", baseOutput: 2, upgradeCostBase: 14000, upgradeOutputBonus: 1, category: "Mining" },
    titanhuette: { name: "Titanium Smelter", baseCost: 68000, produces: "titan", baseOutput: 1, upgradeCostBase: 25000, upgradeOutputBonus: 1, category: "Mining" },
    platinmine: { name: "Platinum Mine", baseCost: 88000, produces: "platin", baseOutput: 1, upgradeCostBase: 32000, upgradeOutputBonus: 1, category: "Mining" },
    chrommine: { name: "Chromium Mine", baseCost: 45000, produces: "chrom", baseOutput: 1, upgradeCostBase: 17000, upgradeOutputBonus: 1, category: "Mining" },
    /* Rare Earths – Mining */
    lanthanmine: { name: "Lanthanum Mine", baseCost: 72000, produces: "lanthan", baseOutput: 1, upgradeCostBase: 26000, upgradeOutputBonus: 1, category: "Mining" },
    cermine: { name: "Cerium Refinery", baseCost: 68000, produces: "cer", baseOutput: 1, upgradeCostBase: 24500, upgradeOutputBonus: 1, category: "Mining" },
    praseodymmine: { name: "Praseodymium Mine", baseCost: 85000, produces: "praseodym", baseOutput: 1, upgradeCostBase: 30000, upgradeOutputBonus: 1, category: "Mining" },
    neodymmine: { name: "Neodymium Mine", baseCost: 92000, produces: "neodym", baseOutput: 1, upgradeCostBase: 33000, upgradeOutputBonus: 1, category: "Mining" },
    promethiummine: { name: "Promethium Refinery", baseCost: 115000, produces: "promethium", baseOutput: 1, upgradeCostBase: 40000, upgradeOutputBonus: 1, category: "Mining" },
    samariummine: { name: "Samarium Mine", baseCost: 78000, produces: "samarium", baseOutput: 1, upgradeCostBase: 28000, upgradeOutputBonus: 1, category: "Mining" },
    europiummine: { name: "Europium Refinery", baseCost: 105000, produces: "europium", baseOutput: 1, upgradeCostBase: 37000, upgradeOutputBonus: 1, category: "Mining" },
    gadoliniummine: { name: "Gadolinium Mine", baseCost: 82000, produces: "gadolinium", baseOutput: 1, upgradeCostBase: 29000, upgradeOutputBonus: 1, category: "Mining" },
    terbiummine: { name: "Terbium Refinery", baseCost: 125000, produces: "terbium", baseOutput: 1, upgradeCostBase: 44000, upgradeOutputBonus: 1, category: "Mining" },
    dysprosiummine: { name: "Dysprosium Mine", baseCost: 98000, produces: "dysprosium", baseOutput: 1, upgradeCostBase: 35000, upgradeOutputBonus: 1, category: "Mining" },
    holmiummine: { name: "Holmium Refinery", baseCost: 88000, produces: "holmium", baseOutput: 1, upgradeCostBase: 31000, upgradeOutputBonus: 1, category: "Mining" },
    erbiummine: { name: "Erbium Mine", baseCost: 84000, produces: "erbium", baseOutput: 1, upgradeCostBase: 30000, upgradeOutputBonus: 1, category: "Mining" },
    thuliummine: { name: "Thulium Refinery", baseCost: 132000, produces: "thulium", baseOutput: 1, upgradeCostBase: 47000, upgradeOutputBonus: 1, category: "Mining" },
    ytterbiummine: { name: "Ytterbium Mine", baseCost: 75000, produces: "ytterbium", baseOutput: 1, upgradeCostBase: 27000, upgradeOutputBonus: 1, category: "Mining" },
    lutetiummine: { name: "Lutetium Refinery", baseCost: 138000, produces: "lutetium", baseOutput: 1, upgradeCostBase: 49000, upgradeOutputBonus: 1, category: "Mining" },
    zementwerk: { name: "Cement Works", baseCost: 35000, produces: "zement", baseOutput: 2, upgradeCostBase: 13000, upgradeOutputBonus: 1, category: "Industry" },
    kalkbrennerei: { name: "Lime Kiln", baseCost: 26500, produces: "kalk", baseOutput: 3, upgradeCostBase: 9800, upgradeOutputBonus: 1, category: "Industry" },
    graphitmine: { name: "Graphite Mine", baseCost: 48000, produces: "graphit", baseOutput: 2, upgradeCostBase: 17500, upgradeOutputBonus: 1, category: "Mining" },
    phosphatmine: { name: "Phosphate Mine", baseCost: 38500, produces: "phosphat", baseOutput: 2, upgradeCostBase: 14200, upgradeOutputBonus: 1, category: "Mining" },
    lithiummine: { name: "Lithium Mine", baseCost: 62000, produces: "lithium", baseOutput: 1, upgradeCostBase: 22800, upgradeOutputBonus: 1, category: "Mining" },
    marmorsteinbruch: { name: "Marble Quarry", baseCost: 52000, produces: "marmor", baseOutput: 1, upgradeCostBase: 19000, upgradeOutputBonus: 1, category: "Mining" },
    uranmine: { name: "Uranium Mine", baseCost: 78000, produces: "uran", baseOutput: 1, upgradeCostBase: 29000, upgradeOutputBonus: 1, category: "Mining" },
    kaschmirzucht: { name: "Cashmere Farm", baseCost: 58000, produces: "kaschmir", baseOutput: 1, upgradeCostBase: 22000, upgradeOutputBonus: 1, category: "Agriculture" },
    chemiefaserwerk: { name: "Chemical Fibre Plant", baseCost: 38000, produces: "synthetik", baseOutput: 2, upgradeCostBase: 14000, upgradeOutputBonus: 1, category: "Industry" },
    safrananbau: { name: "Saffron Farm", baseCost: 92000, produces: "safran", baseOutput: 1, upgradeCostBase: 35000, upgradeOutputBonus: 1, category: "Agriculture" },
    truffelsuche: { name: "Truffle Hunt", baseCost: 82000, produces: "truffel", baseOutput: 1, upgradeCostBase: 31000, upgradeOutputBonus: 1, category: "Agriculture" },
    muschelfarm: { name: "Shellfish Farm", baseCost: 24000, produces: "muscheln", baseOutput: 2, upgradeCostBase: 9000, upgradeOutputBonus: 1, category: "Forestry & Fishing" },
    miningfarm: { name: "Mining Farm", baseCost: 1285000, produces: "bitcoin", baseOutput: 1, upgradeCostBase: 100000, upgradeOutputBonus: 1, category: "Industry", minLevel: 10 },
    ethereumnode: { name: "Ethereum Node", baseCost: 980000, produces: "ethereum", baseOutput: 1, upgradeCostBase: 85000, upgradeOutputBonus: 1, category: "Industry", minLevel: 12 },
    litecoinmine: { name: "Litecoin Mine", baseCost: 420000, produces: "litecoin", baseOutput: 2, upgradeCostBase: 38000, upgradeOutputBonus: 1, category: "Industry", minLevel: 11 },
    ripplevalidator: { name: "Ripple Validator", baseCost: 750000, produces: "ripple", baseOutput: 3, upgradeCostBase: 62000, upgradeOutputBonus: 1, category: "Industry", minLevel: 13 },
    cardanostaking: { name: "Cardano Staking Pool", baseCost: 380000, produces: "cardano", baseOutput: 4, upgradeCostBase: 35000, upgradeOutputBonus: 1, category: "Industry", minLevel: 12 },
    solanavalidator: { name: "Solana Validator", baseCost: 1100000, produces: "solana", baseOutput: 1, upgradeCostBase: 95000, upgradeOutputBonus: 1, category: "Industry", minLevel: 14 },
    dogecoinmine: { name: "Dogecoin Mine", baseCost: 280000, produces: "dogecoin", baseOutput: 5, upgradeCostBase: 22000, upgradeOutputBonus: 2, category: "Industry", minLevel: 10 },
    polkadotnode: { name: "Polkadot Node", baseCost: 520000, produces: "polkadot", baseOutput: 2, upgradeCostBase: 45000, upgradeOutputBonus: 1, category: "Industry", minLevel: 12 },
    avalanchenode: { name: "Avalanche Node", baseCost: 340000, produces: "avalanche", baseOutput: 3, upgradeCostBase: 30000, upgradeOutputBonus: 1, category: "Industry", minLevel: 11 },
    chainlinknode: { name: "Chainlink Node", baseCost: 195000, produces: "chainlink", baseOutput: 4, upgradeCostBase: 18000, upgradeOutputBonus: 1, category: "Industry", minLevel: 11 },
    /* Real Estate – rent every 7 days, no upgrade (~1% of value per week, ~52% p.a.) */
    small_house: { name: "Small House", baseCost: 28000, category: "Real Estate", rent: 280 },
    cottage: { name: "Cottage", baseCost: 22000, category: "Real Estate", rent: 220 },
    apartment: { name: "Apartment", baseCost: 45000, category: "Real Estate", rent: 450 },
    villa: { name: "Villa", baseCost: 185000, category: "Real Estate", rent: 1850 },
    multifamily_house: { name: "Multi-Family House", baseCost: 120000, category: "Real Estate", rent: 1200 },
    penthouse: { name: "Penthouse", baseCost: 420000, category: "Real Estate", rent: 4200 },
    apartment_block: { name: "Apartment Block", baseCost: 380000, category: "Real Estate", rent: 3800 },
    swimming_pool: { name: "Swimming Pool", baseCost: 95000, category: "Real Estate", rent: 950 },
    cinema: { name: "Cinema", baseCost: 240000, category: "Real Estate", rent: 2400 },
    bank_branch: { name: "Bank Branch", baseCost: 350000, category: "Real Estate", rent: 3500 },
    office_building: { name: "Office Building", baseCost: 280000, category: "Real Estate", rent: 2800 },
    hotel: { name: "Hotel", baseCost: 320000, category: "Real Estate", rent: 3200 },
    shopping_mall: { name: "Shopping Mall", baseCost: 580000, category: "Real Estate", rent: 5800 },
    parking_garage: { name: "Parking Garage", baseCost: 88000, category: "Real Estate", rent: 880 },
    restaurant: { name: "Restaurant", baseCost: 75000, category: "Real Estate", rent: 750 },
    gym: { name: "Gym", baseCost: 65000, category: "Real Estate", rent: 650 },
    warehouse: { name: "Warehouse", baseCost: 52000, category: "Real Estate", rent: 520 },
    storage_unit: { name: "Storage Unit", baseCost: 18000, category: "Real Estate", rent: 180 },
  };

  const BUILDING_CATEGORY_ORDER = ["Agriculture", "Forestry & Fishing", "Mining", "Industry", "Real Estate"];

  Object.assign(window.Game, {
    GOODS,
    GOODS_CATEGORY_ORDER,
    BUILDING_TYPES,
    BUILDING_CATEGORY_ORDER,
    INCOME_INTERVAL_SEC: 24,
    XP_PER_DAY: 5,
    STORAGE_KEY: "wirtschaftssim_save",
    UI_STORAGE_KEY: "wirtschaftssim_ui",
    PRICE_HISTORY_DAYS: 90,
  });
})();
